# Generated by Django 3.1 on 2024-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20240503_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
